spring:
  application:
    name: WAF
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create-drop, none, create

    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8080